import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <header style={{height:"60px", backgroundColor:"antiquewhite",color:"black",textAlign:"center"}}>
          <div style={{display:"flex",height:"100%",gap:"3rem",justifyContent:"center" ,alignItems:"center"}}>
            <Link href="/">HOME</Link>
            <Link href="/products">PRODUCTS</Link>
          </div>
        </header>
        {children}
        <footer style={{position:"fixed",left:"0",bottom:"0",background:"gray",display:"flex"}}>Copyright @2025</footer>
      </body>
    </html>
  );
}
