import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <header style={{height:"60px", backgroundColor:"antiquewhite",color:"black",textAlign:"center"}}>This is the header of the page.</header>
        {children}
        <footer style={{position:"fixed",left:"0",bottom:"0",background:"gray",display:"flex"}}>Copyright @2025</footer>
      </body>
    </html>
  );
}
